language: ruby
rvm:
  - 2.6.6

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
  - rake db:migrate

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rails webpacker:compile
  - bundle exec rails test test/models/produto_test.rb
  - bundle exec rails test test/models/cliente_test.rb
  - bundle exec rails test test/models/user_test.rb
  - bundle exec rails test test/models/venda_test.rb  
  - bundle exec cucumber features/cliente.feature
  - bundle exec cucumber features/user.feature
  - bundle exec cucumber features/produto.feature
  